const googUrls = [
    'https://photos.app.goo.gl/hLLgwLv3WNDKBe7c6',    
]

const imageUrls = [
    ['images/cali/bird_bro.webp', 'At least I\'m not an albatross'],
    ['images/cali/bird1.webp', 'Young Western Gull?'],
    ['images/cali/bird2.webp', 'Young Western Gull?'],
    ['images/cali/milpitas_station.webp', 'Milpitas Station'],
    ['images/cali/milpitas.webp', 'Milpitas Station Platform'],
    ['images/cali/monk.webp', 'Monk!'],
    ['images/cali/no_wingtip_flare.webp', 'No wingtip vortex guy!'],
    ['images/cali/pay_milpitas.webp', 'Milpitas Ticketing Station'],
    ['images/cali/shipping1.webp', 'Container shipping!'],
    ['images/cali/shipping2.webp', 'Container shipping!'],
    ['images/cali/windy.webp', 'SF is very windy!'],
    ['images/cars/blue_guy.webp', 'Almost looks like a hotweels type thing!'],
    ['images/cars/brown_chevy.webp', 'Orange? Brown? Brown.'],
    ['images/cars/colorado_parking.webp', 'THE HYUNDAI IONIQ 5'],
    ['images/cars/mitsubishi.webp', 'WOW!'],
    ['images/cars/red_chevy.webp', 'Why the short face?'],
    ['images/cars/van_world.webp', 'Me when my fuel pump relay and alternator and various pulleys DIE'],
    ['images/cats/frijol_flag_comp.webp', 'Supervisor checking in'],
    ['images/cats/frijol_flag.webp', 'Supervisor concerned with my progress...'],
    ['images/cats/frijol_moving.webp', 'Tired from moving in!'],
    ['images/cats/frijol_sleepy.webp', 'Taking in some sun!'],
    ['images/chicago/chinatown_bakery.webp', 'PORK BUN'],
    ['images/chicago/chinatown_neon.webp', 'Dim sum!'],
    ['images/chicago/cta.webp', 'Chicago Transit Authority'],
    ['images/denmark/arches.webp', 'Kunsthal Charlottenborg - Beautiful Arches'],
    ['images/denmark/cool_house.webp', 'Hans Christian Andersen Museum'],
    ['images/denmark/danish_forest_park.webp', 'Park in Odense'],
    ['images/denmark/danish_rows.webp', 'Typical sightseeing in Copenhagen'],
    ['images/denmark/harbor.webp', 'Copenhagen Harbor!'],
    ['images/denmark/kahoot.webp', 'Kahoot! office in Copenhagen'],
    ['images/denmark/mcdonals.webp', 'Danish McDonald'],
    ['images/denmark/pas_pa.webp', 'PAS PA!'],
    ['images/denmark/peugeot_106_GTI.webp', 'Peugeot 106 GTI in Odense'],
    ['images/denmark/right_side_drive.webp', 'MG Midget?'],
    ['images/geneseo/horse_1.webp', 'Why the long face?'],
    ['images/geneseo/horse_2.webp', 'Chillin, straight up hoofin \'it\''],
    ['images/geneseo/rip_tl.webp', 'RIP 2004 Acura TL'],
    ['images/grad/alma.webp', 'Alma!'],
    ['images/grad/bicycle.webp', 'Early morning shot of Hallene Gateway'],
    ['images/grad/bikes_porch.webp', 'Early morning shot of the porch'],
    ['images/grad/grainger.webp', 'test'],
    ['images/grad/grainger_2.webp', 'Across the street from Ceramics, looking north on S Goodwin'],
    ['images/grad/learning_and_labor.webp', 'Hallene Gateway!'],
    ['images/grad/loomis.webp', 'LOOOOOOOOOMIS'],
    ['images/grad/math.webp', 'Altgeld'],
    ['images/grad/mcdicks.webp', 'McDonald on green ft. DJ'],
    ['images/grad/veoride.webp', '\'AY THAT\'S MY VEORIDE!'],
    ['images/grad/wow_apt.webp', 'Gorgeous'],
    ['images/hk/bright.webp', 'SPLENDOR'],
    ['images/hk/buddhe.webp', 'Buddha guy'],
    ['images/hk/chicken.webp', 'uhhh, chicken'],
    ['images/hk/ck.webp', 'Circle K'],
    ['images/hk/flower.webp', 'Nice flower'],
    ['images/hk/gates.webp', 'cool gate'],
    ['images/hk/hk_pa.webp', 'You just gotta keep waving'],
    ['images/hk/mnt.webp', 'Lil hike'],
    ['images/hk/temple.webp', 'cool temple'],
    ['images/joke_machine/beams.webp', 'Q: What keeps the moon in place? A: Its beams!'],
    ['images/joke_machine/broco.webp', 'Q: ¿Cual es el nombre del hemano vegetariano de Bruce Lee? A: Broco Lee!'],
    ['images/joke_machine/hare.webp', 'Q: What do you call a parade of rabbits hopping backward? A: A receding hare-line!'],
    ['images/joke_machine/moon.webp', 'Q: Did you hear about the restaurant on the moon? A: It has great food, but no atmosphere!'],
    ['images/joke_machine/nose.webp', 'Q: What do you call a person with no body and no nose? A: Nobody knows!'],
    ['images/joke_machine/vacas.webp', 'Q: ¿Cuales son cinco cosas que conengan leche? A: Cinco vacas!'],
    ['images/mex/arbol_naranja_2.webp', 'Naranjas!'],
    ['images/mex/arbol_naranja.webp', 'Naranjas!'],
    ['images/mex/asc.webp', 'Caza, Tiro, y Pesca'],
    ['images/mex/bidet.webp', 'Cat Bidet'],
    ['images/mex/carril.webp', 'La Reforma'],
    ['images/mex/casa.webp', 'Great skies'],
    ['images/mex/cfe.webp', 'Comision Federal de Electricidad'],
    ['images/mex/flor.webp', 'Flor!'],
    ['images/mex/gato_naranja.webp', 'Garfield!'],
    ['images/mex/gato.webp', 'Cat chair'],
    ['images/mex/git.webp', 'Ventana'],
    ['images/mex/ladrillo.webp', 'Cochera'],
    ['images/mex/mont.webp', 'Cerro'],
    ['images/mex/naranja.webp', 'Sunset'],
    ['images/mex/oxxo.webp', 'OXXO! OXXO! OXXO!'],
    ['images/mex/pemex.webp', 'Gasolinera'],
    ['images/mex/porto.webp', 'Porton'],
    ['images/mex/torreon.webp', 'Carretera'],
    ['images/mex/usalo.webp', 'USALO!'],
    ['images/miata/front.webp', ':0'],
    ['images/miata/interior.webp', 'mesa'],
    ['images/michigan/2.webp', '2!'],
    ['images/michigan/caterpillar.webp', 'Fuzzy caterpillar'],
    ['images/michigan/fuzzy_caterpillar.webp', 'Fuzzy caterpillar'],
    ['images/michigan/chairs.webp', 'Plastic chairs'],
    ['images/michigan/no_skateboarding.webp', 'No Skateboarding!'],
    ['images/michigan/pet_waste.webp', 'Please keep this area clean!'],
    ['images/michigan/plant_dirt.webp', 'Interesting orange guys'],
    ['images/michigan/river.webp', 'River'],
    ['images/michigan/spider.webp', 'Spider!'],
    ['images/michigan/spider_maybe.webp', 'Spider?'],
    ['images/michigan/waves.webp', 'Wavy'],
    ['images/monkeys/actually_just_scratching.webp', 'quick scratch'],
    ['images/monkeys/butts.webp', 'Put that thing away!'],
    ['images/monkeys/CHASING_ME.webp', 'Low key kinda scary'],
    ['images/monkeys/disbelief.webp', 'Disbelief'],
    ['images/monkeys/golden_monkey.webp', 'Got places to be!'],
    ['images/monkeys/jump.webp', 'On the move'],
    ['images/monkeys/little_guy_schocked.webp', 'AHHHH'],
    ['images/monkeys/little_nippy.webp', 'Quick bite'],
    ['images/monkeys/little_tree_yellow_lips.webp', 'Beady ahh eyes'],
    ['images/monkeys/mr_chill_solo.webp', 'Thanks for being so chill, Mr. Chill'],
    ['images/monkeys/orange_peel.webp', 'mmmmm, orang'],
    ['images/monkeys/stairs.webp', 'moving fast'],
    ['images/monkeys/statue.webp', 'Anatomically correct'],
    ['images/monkeys/swag.webp', 'Swag'],
    ['images/monkeys/tree_chiller.webp', '#MonitoringTheSituation'],
    ['images/other_animals/shy_turtle.webp', 'Performance anxiety'],
    ['images/rando/fog.webp', 'Cerro'],
    ['images/rando/mazda_3.webp', 'RIP 2019 Mazda 3'],
    ['images/rando/miata.webp', '2007 Mazda MX-5 Miata, 6-speed, PRHT'],
    ['images/rando/moving.webp', 'Moving sucks'],
    ['images/rando/sporting_goods.webp', 'Sporting Goods (decrepit)'],
    ['images/rando/van.webp', 'Mason\'s van!'],
    ['images/trains/watch_your_step.webp', 'Watch your step!'],
    ['images/vandenbergish/night_sky.webp', 'Long exposure night sky'],
    ['images/vandenbergish/observatory.webp', 'Vandenberg Observatory'],
    ['images/vandenbergish/radioactive.webp', 'Potentially radioactive?'],
    ['images/vandenbergish/sanguich.webp', 'Sanguich'],
    ['images/vandenbergish/slc.webp', 'SLC 6'],
    ['images/vandenbergish/slide.webp', 'SLC 4 slide'],
    ['images/vandenbergish/thor.webp', 'Thor?'],
    ['images/work/d3.webp', 'A D3 dozer with our teleop system'],
    ['images/work/j8.webp', 'A J8 with our mapping / sensing'],
];

// Function to change the background image
function change_landing_section_background() {
    // Get the hero section element by its ID
    const landing_image = document.getElementById('landing-image');

    if (landing_image) { // Ensure the section element exists
        // Get a random image URL from the array
        const randomIndex = Math.floor(Math.random() * imageUrls.length);
        const randomImageUrl = imageUrls[randomIndex][0];

        // Set the background image style of the section
        landing_image.src = imageUrls[randomIndex][0];
        landing_image.alt = imageUrls[randomIndex][1];
        landing_image.title = imageUrls[randomIndex][1];


        console.log(`Background image changed to: ${randomImageUrl}`);
    }
}

// Function to change the background image on click

// Call changeDisplayedImage when the page loads
window.addEventListener('load', change_landing_section_background);